.PHONY: all build clean format lint

all: build

build:
	@echo "Building project..."
	cargo build

clean:
	@echo "Cleaning project..."
	cargo clean

format:
	cargo fmt

lint:
	@echo "Linting code..."
	cargo clippy

