name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Recursively run tests for each project
      - name: Run tests for all projects
        run: |
          find . -name "Cargo.toml" -execdir cargo test --verbose \;

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      # Recursively build each project
      - name: Build all projects
        run: |
          find . -name "Cargo.toml" -execdir cargo build --verbose \;